services:
  # DATABASE
  db-warehouse:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      # Tips: MySQL image bawaan hanya buat 1 DB. 
      # Untuk 2 DB, kita gunakan trik script init sederhana
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  # EUREKA
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"

  # MICROSERVICES
  product-catalogue:
    build: ./product-catalouge-service
    depends_on:
      - service-registry
      - db-warehouse
    environment:
      EUREKA_SERVER: http://service-registry:8761/eureka
      DB_HOST: db-warehouse

  inventory-service:
    build: ./inventory-service
    depends_on:
      - service-registry
      - db-warehouse
    environment:
      EUREKA_SERVER: http://service-registry:8761/eureka
      DB_HOST: db-warehouse

  # GATEWAY
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER: http://service-registry:8761/eureka